version: "3.8"

services:
  backend:
    build: ./backend
    container_name: house_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: house_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
